#!/usr/bin/perl
use strict;
BEGIN { # этой конструкцией определяем путь к скрипту, в том числе на этапе компиляции,
        # делаем путь доступным глобально в скрипте, добавляем путь к библиотеке
    use File::Basename; use Cwd 'abs_path';
    use vars '$self_path'; $self_path=dirname(abs_path("$0")); push @INC, "$self_path/../../modules";
}
use firewall;

umask 0077; # для безопасности
select STDERR; $| = 1; # make unbuffered
select STDOUT; $| = 1; # make unbuffered

our $cfg_name  = "main";
our $mod_path  = "$self_path/../../modules";
our $conf_path = "$self_path/conf";

print "Setting up SNAT...\n";

exit 1 if init($cfg_name,"$conf_path/networks.conf") !=0;
load_rules_from_file("$conf_path/rules_nat_snat");