#!/bin/sh

echo "  Configuring sysctl:"
### CONF
echo "    accept_redirects"
echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects
echo "    arp_ignore"
echo 2 > /proc/sys/net/ipv4/conf/all/arp_ignore
echo "    forwarding"
echo 1 > /proc/sys/net/ipv4/conf/all/forwarding
echo "    rp_filter (RFC1812)"
echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
echo "    disabling the logging of martians"
echo 0 > /proc/sys/net/ipv4/conf/all/log_martians
echo "    disable ICMP send_redirect"
if [ -e /proc/sys/net/ipv4/conf/all/send_redirects ]; then
    for interface in /proc/sys/net/ipv4/conf/*/send_redirects; do
	echo 0 > $interface
    done
fi
echo "    enabling protection against source routed packets"
for interface in /proc/sys/net/ipv4/conf/*/accept_source_route; do
    echo 0 > $interface
done
echo "    setting default conntrack timeouts"
echo 60 > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout
echo 180 > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout_stream

echo "    enabling reduction of the DoS'ing ability"
echo 10 > /proc/sys/net/ipv4/tcp_fin_timeout
echo 1800 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 0 > /proc/sys/net/ipv4/tcp_window_scaling
echo 0 > /proc/sys/net/ipv4/tcp_sack

### IP
echo "    ip_forward"
echo 1 > /proc/sys/net/ipv4/ip_forward
### TCP
echo "    tcp_ecn"
echo 0 > /proc/sys/net/ipv4/tcp_ecn
echo "    tcp-syncookies"
echo 1 > /proc/sys/net/ipv4/tcp_syncookies
# tcp_max_syn_backlog, tcp_synack_retries, tcp_abort_on_overflow.
### UDP
### ICMP
echo "    icmp_echo_ignore_broadcasts"
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
echo "    icmp_ignore_bogus_error_responses"
echo 1 > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses