#!/bin/sh

echo "Setting up tc for eth0..."

### LAN ######################################################################
# redirect 2 ifb0
tc qdisc del dev eth0 root >/dev/null 2>&1
tc qdisc del dev eth0 ingress > /dev/null 2>&1
tc qdisc add dev eth0 root handle 1: prio
tc filter add dev eth0 parent 1: protocol ip u32 match u32 0 0 action mirred egress redirect dev ifb0
