#!/bin/sh

echo "Setting up routing via ISP2..."

# cleaning
ip route flush table inet2 >/dev/null 2>&1
ip rule del to 198.51.100.18 table inet2 >/dev/null 2>&1
ip rule del from all fwmark 0x4 table inet2 >/dev/null 2>&1

# setting
ip route add default via 192.168.5.10 dev eth3 table inet2
ip rule add to 198.51.100.18 table inet2
ip rule add from all fwmark 0x4 table inet2
ip route flush cache